name: Deploy to server

on:
  push:
    branches: [ master ]   # если у тебя ветка master — поменяй здесь на master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project to server via rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            --exclude=".git" \
              --exclude="venv" \
              --exclude="data/*.json" \
              --exclude="data/*.lock" \
              --exclude="data/*.bak" \
              --exclude="static/img/guest_photos/" \
              --exclude="static/uploads/guests/" \
              ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}



      - name: Run simple remote check
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -la ${{ secrets.DEPLOY_PATH }}"

      - name: Install requirements and restart service
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
              cd ${{ secrets.DEPLOY_PATH }} && \
              source venv/bin/activate && \
              pip install -r requirements.txt && \
              sudo systemctl restart koshkina \
            "
